FROM nvidia/cuda:9.1-cudnn7-runtime

ENV CONDA_VERSION "5.0.1"
ENV PATH "/root/anaconda3/bin:$PATH"

RUN apt-get update -y \
 && apt-get install -y curl git build-essential

RUN curl -O https://repo.continuum.io/archive/Anaconda3-${CONDA_VERSION}-Linux-x86_64.sh \
 && bash Anaconda3-${CONDA_VERSION}-Linux-x86_64.sh -b \
 && conda install -y numpy matplotlib jupyter scipy scikit-learn seaborn \
                  tensorflow keras pymc3
