#!/bin/bash

DOCKER_FLAGS=
IMAGE_TAG=cpu-latest

if [[ "$GPU" = 1 ]]; then
  DOCKER_FLAGS='--runtime=nvidia'
  IMAGE_TAG=gpu-latest
fi

docker run ${DOCKER_FLAGS} --rm -it \
  -v $PWD:/tmp/working \
  -w=/tmp/working \
  -p 8888:8888  \
  agatan/ml-python:${IMAGE_TAG} \
  $@

